### PR TITLE
fix accessing an implicitly unwrapped optional that’s nil

### PR DESCRIPTION
**Pull request by xcoderliu**
access unwarp optional value will get EXC_BAD_INSTRUCTION

### CODE REVIEW

**Comment by nfgrilo** [comment]
Thanks @xcoderliu - I will soon review and merge it!

**Comment by xcoderliu** [comment]
image

**Comment by xcoderliu** [comment]
still have this error

**Comment by nfgrilo** [comment]
@xcoderliu could you please let me know macOS version and Swift version?

**Pull request closed without merging**
